from __future__ import annotations

import importlib

EXPECTED_EXPORTS: dict[str, tuple[str, ...]] = {
    "thesis_bench.pilot": (
        "AnswerContract",
        "AuditMethod",
        "AuditOutcome",
        "C2EligibilityManifest",
        "C2EligibilityMetadata",
        "C2FreezeIdentity",
        "Comparator",
        "ComparatorRecord",
        "ConditionAnalysisContract",
        "ConditionApplicability",
        "ContaminationAudit",
        "ContaminationEvidence",
        "DeterministicEvaluationEvidence",
        "FamilyRecord",
        "FairnessEvidence",
        "HeadroomEvidence",
        "HeadroomStratumEvidence",
        "HumanCalibrationEvidence",
        "InvalidityEvidence",
        "KindEvidence",
        "Language",
        "MetricApplicability",
        "PilotManifest",
        "ProgressCriterion",
        "ProgressEvidence",
        "ProgressObservation",
        "ProgressionReport",
        "ProtectedArtifactReference",
        "ResearcherFeasibilityEvidence",
        "SolvabilityEvidence",
        "TargetStratum",
        "TargetStratumRecord",
        "TaskClass",
        "VariantRecord",
        "VariantType",
        "W1Evidence",
        "derive_progression",
        "load_pilot_manifest",
        "model_facing_manifest",
        "validate_c2_eligibility",
        "validate_composition",
        "validate_pilot_manifest",
    ),
    "thesis_bench.evaluation": (
        "AdjudicationRecord",
        "AppendOnlyAdjudicationStore",
        "ArtifactIdentity",
        "CalibrationStatus",
        "CalibrationSummary",
        "DeterministicFixture",
        "EvaluatorIdentity",
        "FixtureCategory",
        "FixtureQualification",
        "FixtureResult",
        "FixtureSetIdentity",
        "InputIdentity",
        "InvalidityClassification",
        "JudgePolicy",
        "JudgeValidation",
        "OutputIdentity",
        "RatingRecord",
        "RubricCriterion",
        "SensitivityInputs",
        "adjudicate_ratings",
        "adjacent_agreement",
        "build_evaluation_record",
        "calibration_summary",
        "classify_invalidity",
        "exact_agreement",
        "family_clustered_interval",
        "import_rating",
        "krippendorff_alpha",
        "qualify_deterministic_evaluator",
        "sensitivity_inputs",
        "validate_judge_policy",
        "validate_rubric",
    ),
    "thesis_bench.cluster": (
        "ActionCapture",
        "ActionRequest",
        "AttemptRecord",
        "ClusterAttempt",
        "ClusterExecutor",
        "ClusterPolicy",
        "ClusterQualification",
        "FakeCluster",
        "FinalStateFixture",
        "FinalStateObservation",
        "FinalStateResult",
        "FinalStateValidator",
        "KindEntryPointRecord",
        "PinnedEnvironment",
        "PolicyComparison",
        "ProcessContainerAdapter",
        "qualify_cluster",
        "compare_neutral_policies",
        "real_kind_qualification_help",
    ),
    "thesis_bench.web": (
        "AllowlistEntry",
        "FakeSearchFetchProvider",
        "FetchMetadata",
        "FetchResponse",
        "PreparedFetch",
        "ProviderEntryPointRecord",
        "RetrievalProvenance",
        "SearchFetchProvider",
        "SearchResult",
        "SourceDriftResult",
        "W1Attempt",
        "W1Budget",
        "W1FeasibilityReport",
        "W1Policy",
        "WebResult",
        "provider_qualification_help",
        "qualify_w1",
        "source_drift_precheck",
    ),
    "thesis_bench.config": (
        "SourceIdentity",
        "ValidatedConfiguration",
        "canonical_json_bytes",
        "discover_project_root",
        "load_configuration",
        "load_yaml_document",
        "semantic_sha256",
        "source_sha256",
        "validate_document",
    ),
    "thesis_bench.provenance": (
        "GitProvenance",
        "Manifest",
        "ManifestEnvironment",
        "ManifestGit",
        "ManifestHashes",
        "ManifestMetadata",
        "ManifestSource",
        "RuntimeEnvironment",
        "build_manifest",
        "capture_environment",
        "capture_git",
        "load_manifest",
        "manifest_semantic_sha256",
        "manifest_to_bytes",
    ),
}


def test_existing_public_exports_remain_available_from_compatibility_facades() -> None:
    for module_name, names in EXPECTED_EXPORTS.items():
        module = importlib.import_module(module_name)
        assert all(hasattr(module, name) for name in names), module_name


def test_public_exports_match_the_pre_refactor_surface() -> None:
    for module_name, names in EXPECTED_EXPORTS.items():
        module = importlib.import_module(module_name)
        assert tuple(module.__all__) == names
